package cn.abcdsxg.app.appJump.Data.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.abcdsxg.app.appJump.Data.greenDao.AppInfo;
import cn.abcdsxg.app.appJump.Data.greenDao.LancherInfo;

import cn.abcdsxg.app.appJump.Data.greenDao.AppInfoDao;
import cn.abcdsxg.app.appJump.Data.greenDao.LancherInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoDaoConfig;
    private final DaoConfig lancherInfoDaoConfig;

    private final AppInfoDao appInfoDao;
    private final LancherInfoDao lancherInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        lancherInfoDaoConfig = daoConfigMap.get(LancherInfoDao.class).clone();
        lancherInfoDaoConfig.initIdentityScope(type);

        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);
        lancherInfoDao = new LancherInfoDao(lancherInfoDaoConfig, this);

        registerDao(AppInfo.class, appInfoDao);
        registerDao(LancherInfo.class, lancherInfoDao);
    }
    
    public void clear() {
        appInfoDaoConfig.clearIdentityScope();
        lancherInfoDaoConfig.clearIdentityScope();
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

    public LancherInfoDao getLancherInfoDao() {
        return lancherInfoDao;
    }

}
