package cn.abcdsxg.app.appJump.Data.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.abcdsxg.app.appJump.Data.greenDao.LancherInfo;
import cn.abcdsxg.app.appJump.Data.greenDao.AppInfo;

import cn.abcdsxg.app.appJump.Data.greenDao.LancherInfoDao;
import cn.abcdsxg.app.appJump.Data.greenDao.AppInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lancherInfoDaoConfig;
    private final DaoConfig appInfoDaoConfig;

    private final LancherInfoDao lancherInfoDao;
    private final AppInfoDao appInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lancherInfoDaoConfig = daoConfigMap.get(LancherInfoDao.class).clone();
        lancherInfoDaoConfig.initIdentityScope(type);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        lancherInfoDao = new LancherInfoDao(lancherInfoDaoConfig, this);
        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);

        registerDao(LancherInfo.class, lancherInfoDao);
        registerDao(AppInfo.class, appInfoDao);
    }
    
    public void clear() {
        lancherInfoDaoConfig.getIdentityScope().clear();
        appInfoDaoConfig.getIdentityScope().clear();
    }

    public LancherInfoDao getLancherInfoDao() {
        return lancherInfoDao;
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

}
